export enum AppConfigs {
  NODE_ENV = 'NODE_ENV',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  CLIENT_ORIGIN = 'CLIENT_ORIGIN',
  PORT = 'PORT',
  HASH_SALT_ROUNDS = 'HASH_SALT_ROUNDS',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRY = 'JWT_EXPIRY',
  MAX_LOGIN_ATTEMPTS = 'MAX_LOGIN_ATTEMPTS',
}
